version: '3.7'
services:  
  redis:
    image: redis:alpine
    command: redis-server --requirepass MyRedisPassword
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017-27019:27017-27019"
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8082:8000"
    environment: 
      REDIS_URL: redis://:MyRedisPassword@redis:6379/0
      MONGODB_URL: mongodb://admin:password@mongodb:27017/admin    
    depends_on: 
      - redis
      - mongodb
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BACKEND_URL: http://localhost:8082
    ports:
      - "8080:5000"
    depends_on:
      - backend

volumes:
  mongodb-data:
    driver: local